channels:
- conda-forge
- gardengroupuo 
#- intel
dependencies:
# Jupyter
- jupyterlab=2
- nodejs=11
- nbconvert=5.5
- widgetsnbextension=3.5
- jupyter_contrib_nbextensions 
- jupyter_nbextensions_configurator
# Python Kernel
- python=3.7
# Python Kernel for Organisms
#- mkl
- pip
- numpy
- scipy
- ase=3.21.1
- asap3=3.11.10
- organisms
